name: Price Tracker

on:
  schedule:
    # ╔═══════════════════════════════════════════════════════════════╗
    # ║  CHANGE THE LINE BELOW to set when your script runs          ║
    # ║                                                                ║
    # ║  Format:  'MINUTE HOUR * * *'                                  ║
    # ║                                                                ║
    # ║  Examples:                                                     ║
    # ║    '0 9 * * *'   = 9:00 AM UTC daily                          ║
    # ║    '30 14 * * *' = 2:30 PM UTC daily                          ║
    # ║    '0 0 * * *'   = Midnight UTC daily                         ║
    # ║                                                                ║
    # ║  Use https://time.is/UTC to find your local time in UTC       ║
    # ╚═══════════════════════════════════════════════════════════════╝
    - cron: '0 0/3 * * *'

  # This adds a "Run workflow" button so you can test manually
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_price_tracker.txt

      - name: Run script
        env:
          # Your secrets are available as environment variables
          # Add more secrets in Settings > Secrets > Actions
          EMAIL_ADDRESS: ${{ secrets.MY_EMAIL }}
          PASSWORD: ${{ secrets.MY_PASSWORD }}
          TO_EMAIL_ADDRESS: ${{ secrets.TO_EMAIL_ADDRESS }}
        run: python price_tracker.py
      - name: Guardar el archivo generado (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: reporte-precios-spotify  # El nombre que verás en la web de GitHub
          path: test.txt                 # El nombre exacto del archivo que crea tu script
          retention-days: 2              # Opcional: Cuántos días quieres que GitHub lo guarde
